Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2020-08, with the labels that each got.

#80 Add a release task to update rpm version/release and changelog and tag
  Gemfile
  Rakefile
Labels: enhancement

#81 Ensure we get all of the expected RPMs from all pages
  lib/manageiq/rpm_build/rpm_repo.rb
Labels: bug, jansa/yes

#82 Ensure that the group has write access to the files and directories
  rpm_spec/subpackages/manageiq-appliance
  rpm_spec/subpackages/manageiq-core
  rpm_spec/subpackages/manageiq-gemset
  rpm_spec/subpackages/manageiq-system
  rpm_spec/subpackages/manageiq-ui
Labels: bug, jansa/yes?

#84 Add s390x repo
  config/options.yml
Labels: enhancement

#85 Add wmi only if x86_64
  rpm_spec/subpackages/manageiq-gemset
Labels: refactoring

#86 Include rpms only for supported arch
  lib/manageiq/rpm_build/rpm_repo.rb
Labels: bug, jansa/yes?
