Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2020-11, with the labels that each got.

#115 Ensure updates to server and zookeeper properties are in config-sample
  packages/kafka/kafka.spec
Labels: enhancement

#116 Allow bundler to do the install with the correct build options
  lib/manageiq/rpm_build/generate_gemset.rb
Labels: enhancement, kasparov/yes?

#118 Replace ovirt-ansible-roles with ovirt-ansible-collection
  rpm_spec/subpackages/manageiq-gemset
Labels: kasparov/yes?

#117 Add libsodium-devel for the appliance_console
  lib/manageiq/rpm_build/generate_gemset.rb
  rpm_spec/subpackages/manageiq-gemset
Labels: bug, kasparov/yes?

#119 Bump kafka version after spec changes in #115
  packages/kafka/kafka.spec
Labels: enhancement

#120 Add git SHAs to gem manifest
  lib/manageiq/rpm_build/generate_gemset.rb
Labels: enhancement

#121 Add dist to ensure it's in the filename
  packages/kafka/kafka.spec
Labels: bug
