Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2020-05, with the labels that each got.

#21 Add rubocop files
  .gitignore
  .rubocop.yml
  .rubocop_cc.yml
  .rubocop_local.yml
Labels: enhancement

#22 Pin to UBI 8.1
  Dockerfile
Labels: bug

#24 Pretty output with colors 🌈
  Gemfile
  README.md
  lib/manageiq/rpm_build.rb
  lib/manageiq/rpm_build/build_copr.rb
  lib/manageiq/rpm_build/generate_core.rb
  lib/manageiq/rpm_build/generate_gemset.rb
  lib/manageiq/rpm_build/generate_tar_files.rb
  lib/manageiq/rpm_build/helper.rb
  lib/manageiq/rpm_build/setup_source_repos.rb
Labels: enhancement

#18 Change to build "manageiq" package with multiple subpackages (RPMs)
  .gitignore
  README.md
  bin/build.rb
  bin/generate_spec.rb
  config/exclude_manageiq
  lib/manageiq/rpm_build.rb
  lib/manageiq/rpm_build/build_copr.rb
  lib/manageiq/rpm_build/generate_core.rb
  lib/manageiq/rpm_build/generate_gemset.rb
  lib/manageiq/rpm_build/generate_tar_files.rb
  rpm_spec/manageiq-appliance/manageiq-appliance.spec
  rpm_spec/manageiq-gemset/manageiq-gemset.spec
  rpm_spec/manageiq.spec.in
  rpm_spec/manageiq/manageiq.spec
  rpm_spec/subpackages/manageiq-appliance
  rpm_spec/subpackages/manageiq-appliance-tools
  rpm_spec/subpackages/manageiq-core
  rpm_spec/subpackages/manageiq-gemset
  rpm_spec/subpackages/manageiq-pods
  rpm_spec/subpackages/manageiq-system
  rpm_spec/subpackages/manageiq-ui
Labels: enhancement

#11 Allow for pluggable public dirs and service ui skins
  lib/manageiq/rpm_build/generate_core.rb
Labels: enhancement

#30 Default the number of bundler tasks to the number of cpus
  lib/manageiq/rpm_build/generate_gemset.rb
Labels: enhancement

#29 Use the config gem to simplify options and overrides
  Gemfile
  config/options.yml
  lib/manageiq/rpm_build.rb
  lib/manageiq/rpm_build/build_copr.rb
  lib/manageiq/rpm_build/generate_core.rb
  lib/manageiq/rpm_build/generate_gemset.rb
  lib/manageiq/rpm_build/generate_tar_files.rb
  lib/manageiq/rpm_build/setup_source_repos.rb
Labels: enhancement

#32 Add hook for post_setup_source_repo
  .gitignore
  lib/manageiq/rpm_build/helper.rb
  lib/manageiq/rpm_build/setup_source_repos.rb
Labels: enhancement

#28 Generate evm_production during rpm build
  evm_override
  evm_productization
  lib/manageiq/rpm_build/setup_source_repos.rb
  rpm_spec/manageiq.spec.in
Labels: enhancement

#33 Add VERSION file support and split app version and rpm version
  config/options.yml
  lib/manageiq/rpm_build.rb
  lib/manageiq/rpm_build/build_copr.rb
  lib/manageiq/rpm_build/generate_core.rb
  lib/manageiq/rpm_build/generate_tar_files.rb
Labels: enhancement

#35 Fix spec file name to use OPTIONS
  lib/manageiq/rpm_build/build_copr.rb
Labels: bug

#40 RPM "Requires" clean up
  rpm_spec/subpackages/manageiq-appliance
  rpm_spec/subpackages/manageiq-core
  rpm_spec/subpackages/manageiq-gemset
  rpm_spec/subpackages/manageiq-pods
  rpm_spec/subpackages/manageiq-system
  rpm_spec/subpackages/manageiq-ui
Labels: wip

#48 Upload built RPMs if credentials are provided
  Gemfile
  bin/build.rb
  config/options.yml
  lib/manageiq/rpm_build.rb
  lib/manageiq/rpm_build/build_uploader.rb
Labels: enhancement

#49 Update rpm repo
  .gitignore
  Dockerfile
  README.md
  bin/build.rb
  config/options.yml
  lib/manageiq/rpm_build.rb
  lib/manageiq/rpm_build/build_uploader.rb
  lib/manageiq/rpm_build/rpm_repo.rb
  lib/manageiq/rpm_build/s3_common.rb
Labels: enhancement
