Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2020-07, with the labels that each got.

#74 Remove pdf-writer demo directory
  scripts/gem_cleanup.sh
Labels: bug

#75 Add webpack manifest
  rpm_spec/manageiq.spec.in
  rpm_spec/subpackages/manageiq-gemset
  rpm_spec/subpackages/manageiq-system
  rpm_spec/subpackages/manageiq-ui
Labels: enhancement

#76 Changes to support ppc64le
  Dockerfile
  lib/manageiq/rpm_build/generate_core.rb
  lib/manageiq/rpm_build/generate_gemset.rb
  rpm_spec/subpackages/manageiq-gemset
Labels: enhancement

#79 Include RC builds in release builds
  config/options.yml
Labels: bug, jansa/yes?
