Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2020-09, with the labels that each got.

#88 Add kafka to the kasparov repos
  config/options.yml
Labels: enhancement

#89 Add webpack manifest for the service ui
  rpm_spec/manageiq.spec.in
  rpm_spec/subpackages/manageiq-ui
Labels: enhancement, jansa/yes?

#87 Use Gemfile.lock.release (if exist) and update plugin revision for nightly build
  bin/build.rb
  lib/manageiq/rpm_build/generate_gemset.rb
Labels: enhancement, jansa/yes?

#90 Include modules manifest
  rpm_spec/manageiq.spec.in
  rpm_spec/subpackages/manageiq-ui
Labels: enhancement, jansa/yes?

#95 Remove PowerTools repo - not used
  Dockerfile
Labels: technical debt
