Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2020-10, with the labels that each got.

#97 Disable subscription-manager globally
  Dockerfile
Labels: refactoring

#100 Don't set version for unf_ext gem
  lib/manageiq/rpm_build/generate_gemset.rb
Labels: bug

#98 Add rpm spec and related files for 3rd party packages
  .gitignore
  packages/kafka/kafka.service
  packages/kafka/kafka.spec
  packages/kafka/zookeeper.service
  packages/python-bambou/python-bambou.spec
  packages/python-pylxca/python-pylxca.spec
  packages/python-vspk/python-vspk.spec
  packages/repmgr10/repmgr-pg10-config-file-location.patch
  packages/repmgr10/repmgr-pg10.init
  packages/repmgr10/repmgr-pg10.service
  packages/repmgr10/repmgr-pg10.sysconfig
  packages/repmgr10/repmgr.spec
  packages/smem/smem-1.5-python3path.patch
  packages/smem/smem.spec
  packages/wmi/openvas-wmi-1.3.14.patch
  packages/wmi/wmi.spec
Labels: enhancement

#101 Add the kafka jaas config to kafka.service
  packages/kafka/kafka.service
Labels: enhancement

#106 Productization support for manageiq-ansible-venv
  packages/manageiq-ansible-venv/Dockerfile
  packages/manageiq-ansible-venv/README.md
  packages/manageiq-ansible-venv/container-assets/build.sh
  packages/manageiq-ansible-venv/manageiq-ansible-venv.spec
Labels: enhancement

#107 Handle python binary symlinks in rpm spec for manageiq-ansible-venv
  packages/manageiq-ansible-venv/container-assets/build.sh
  packages/manageiq-ansible-venv/manageiq-ansible-venv.spec
Labels: bug

#94 Adding zLinux(s390x) support
  Dockerfile
  lib/manageiq/rpm_build/generate_core.rb
  lib/manageiq/rpm_build/generate_gemset.rb
Labels: enhancement

#109 adding ppc64le support in manageiq-ansible-venv
  packages/manageiq-ansible-venv/Dockerfile
Labels: enhancement

#108 Add manifest for manageiq-ansible-venv
  packages/manageiq-ansible-venv/Dockerfile
  packages/manageiq-ansible-venv/README.md
  packages/manageiq-ansible-venv/container-assets/build.sh
  packages/manageiq-ansible-venv/manageiq-ansible-venv.spec
Labels: enhancement

#110 DNF command cleanup
  Dockerfile
  packages/manageiq-ansible-venv/Dockerfile
Labels: technical debt
