Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2021-12, with the labels that each got.

#227 Fix rake release after rake task was moved
  lib/tasks/release.rake
Labels: bug, morphy/yes

#228 Allow for signed tags with automatic messages
  lib/tasks/release.rake
Labels: enhancement, morphy/yes

#229 Fix RPM repo includes
  .rspec
  .travis.yml
  Gemfile
  Rakefile
  config/options.yml
  spec/config/options_spec.rb
  spec/spec_helper.rb
Labels: bug, enhancement, test

#230 [MORPHY] Fix RPM repo includes
  .rspec
  .travis.yml
  Gemfile
  Rakefile
  config/options.yml
  spec/config/options_spec.rb
  spec/spec_helper.rb
Labels: bug, enhancement, test

#231 Pull the major version from the config file
  spec/config/options_spec.rb
Labels: test

#234 Fix active_support require
  lib/manageiq/rpm_build/generate_core.rb
Labels: bug, morphy/yes?

#235 Initial attempt at Github Actions
  .github/workflows/ci.yaml
Labels: test

#236 Fix invalid workflow file syntax
  .github/workflows/ci.yaml
  .travis.yml
  README.md
Labels: test

#238 [WIP] Cleanup GitHub Actions
  .github/workflows/ci.yaml
Labels: wip

#240 Fix TRAVIS env vars
  .github/workflows/ci.yaml
Labels: test

#241 Remove TRAVIS env vars entirely
  .github/workflows/ci.yaml
  bin/build_container_image
Labels: test
