Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2021-03, with the labels that each got.

#138 Move kafka logs to /var/log
  packages/kafka/kafka.service
Labels: enhancement

#139 glusterfs-fuse is required for scanning GlusterFS datastores
  rpm_spec/subpackages/manageiq-gemset
Labels: dependencies

#134 Copy systemd unit files from plugin repos
  rpm_spec/manageiq.spec.in
  rpm_spec/subpackages/manageiq-appliance
  rpm_spec/subpackages/manageiq-core-services
  rpm_spec/subpackages/manageiq-gemset-services
Labels: technical debt

#136 Remove sqlite
  Dockerfile
  rpm_spec/subpackages/manageiq-gemset
Labels: technical debt

#91 Add dependency on the kafka package
  rpm_spec/subpackages/manageiq-appliance
Labels: dependencies, enhancement, kasparov/no
