Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2021-07, with the labels that each got.

#161 Resources owned by user manageiq for non-root appliances
  rpm_spec/manageiq.spec.in
  rpm_spec/subpackages/manageiq-core
  rpm_spec/subpackages/manageiq-ui
Labels: enhancement

#162 Fix production over-writing sti_loader.yml
  lib/manageiq/rpm_build/generate_core.rb
  rpm_spec/manageiq.spec.in
  rpm_spec/subpackages/manageiq-core
Labels: bug

#164 Fix downstream RPM build
  lib/manageiq/rpm_build/generate_core.rb
Labels: bug

#163 Add mod_ssl in case we need to run with SSL
  rpm_spec/subpackages/manageiq-ui
Labels: enhancement

#166 Remove . from RPM release number
  README.md
  config/options.yml
  lib/manageiq/rpm_build/build_copr.rb
Labels: bug, kasparov/yes?, lasker/yes?

#165 Fix the gemset prefix for downstream builds
  lib/manageiq/rpm_build/generate_core.rb
Labels: bug

#167 Upgrade to UBI 8.4 and switch to CentOS Stream 8
  packages/manageiq-ansible-venv/Dockerfile
Labels: dependencies

#168 Followup from #166
  config/options.yml
Labels: bug, kasparov/yes?, lasker/yes?

#169 Manually backport #151
  Dockerfile
Labels: bug

#170 Remove creation of log dir
  lib/manageiq/rpm_build/generate_gemset.rb
Labels: technical debt

#173 Return descendent loader cache to regular privs
  rpm_spec/subpackages/manageiq-core
Labels: enhancement
