Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2021-06, with the labels that each got.

#156 Add dnf update to get updated packages for s390x arch
  Dockerfile
Labels: enhancement

#154 Move to CentOS Stream
  Dockerfile
Labels: enhancement, lasker/no

#152 add common usage examples
  .dockerignore
  README.md
Labels: documentation

#158 add manageiq-initialize to rpm
  rpm_spec/subpackages/manageiq-system
Labels: refactoring

#160 Update libarchive to 3.3.3-1 to avoid rugged install failure
  Dockerfile
Labels: bug, dependencies, jansa/yes?, kasparov/yes?, lasker/yes?

#157 create manageiq user and fix directories
  rpm_spec/manageiq.spec.in
  rpm_spec/subpackages/manageiq-appliance
  rpm_spec/subpackages/manageiq-core
  rpm_spec/subpackages/manageiq-gemset
  rpm_spec/subpackages/manageiq-system
  rpm_spec/subpackages/manageiq-ui
Labels: enhancement
