Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2021-11, with the labels that each got.

#223 [MORPHY] Fix manageiq-release references
  Dockerfile
  lib/tasks/release.rake
  packages/manageiq-release/manageiq-13-morphy.repo
  packages/manageiq-release/manageiq-release.spec
Labels: bug

#192 Update lockfiles
  bin/generate_core_lockfile.rb
Labels: enhancement

#181 remove cockpit
  rpm_spec/subpackages/manageiq-appliance
  rpm_spec/subpackages/manageiq-core
  rpm_spec/subpackages/manageiq-system
Labels: technical debt

#224 Remove subscription-manager
  Dockerfile
Labels: bug, morphy/yes?

#225 [MORPHY] Remove subscription-manager
  Dockerfile
Labels: bug
