Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2021-09, with the labels that each got.

#182 Fixes for v14
  config/options.yml
  lib/tasks/release.rake
  packages/manageiq-release/README.md
  packages/manageiq-release/manageiq-release.spec
Labels: bug

#183 Add travis script to build the rpm_build container image
  .travis.yml
  bin/build_container_image
Labels: enhancement

#184 Travis build script updates
  bin/build_container_image
Labels: enhancement

#187 [MORPHY] Fix production over-writing sti_loader.yml
  lib/manageiq/rpm_build/generate_core.rb
  rpm_spec/manageiq.spec.in
  rpm_spec/subpackages/manageiq-core
Labels: bug

#177 Reduce disk space of locale files
  lib/manageiq/rpm_build/generate_core.rb
Labels: enhancement

#188 rpm install: Don't warn for missing files
  rpm_spec/subpackages/manageiq-core
  rpm_spec/subpackages/manageiq-ui
Labels: bug

#185 Replace rake update_{stop,start} with systemctl try-restart evmserverd
  rpm_spec/subpackages/manageiq-appliance
Labels: enhancement

#180 Don't install gitkeep files
  config/exclude_gemset
  config/exclude_manageiq
  lib/manageiq/rpm_build/generate_tar_files.rb
Labels: enhancement

#191 [MORPHY] Remove . from RPM release number
  README.md
  lib/manageiq/rpm_build/build_copr.rb
Labels: bug

#197 [MORPHY] Add back missing evm-watchdog.service
  rpm_spec/subpackages/manageiq-appliance
Labels: bug

#195 Only chown files if files exist
  rpm_spec/subpackages/manageiq-ui
Labels: bug

#198 [MORPHY] Followup from #166
  config/options.yml
Labels: bug

#201 Allow building on Z(s390x)
  Dockerfile
Labels: bug

#202 Remove postfix dependency since the application does not rely on it
  rpm_spec/subpackages/manageiq-system
Labels: dependencies, morphy/yes?

#189 Fix URLs for Najdorf nightly
  packages/manageiq-release/manageiq-14-najdorf.repo
  packages/manageiq-release/manageiq-release.spec
Labels: bug

#204 Prefer using npm.manageiq.org as a proxy cache for yarn
  config/options.yml
Labels: performance
