Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2021-05, with the labels that each got.

#145 Use properties file for environmental variables
  rpm_spec/manageiq.spec.in
  rpm_spec/subpackages/manageiq-gemset
  rpm_spec/subpackages/manageiq-system
Labels: enhancement

#150 spell productization correctly
  rpm_spec/manageiq.spec.in
Labels: technical debt

#151 Don't attempt to pull rpm* packages from ubi-8 repos
  Dockerfile
Labels: bug

#153 Update to UBI 8.4
  Dockerfile
Labels: dependencies
