Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2022-11, with the labels that each got.

#309 Add support for building repmgr13 v 5.2.1
  config/options.yml
  packages/repmgr13/Dockerfile
  packages/repmgr13/container-assets/build.sh
  packages/repmgr13/repmgr-pg13-config-file-location.patch
  packages/repmgr13/repmgr-pg13.init
  packages/repmgr13/repmgr-pg13.service
  packages/repmgr13/repmgr-pg13.sysconfig
  packages/repmgr13/repmgr.spec
  rpm_spec/subpackages/manageiq-appliance
Labels: enhancement

#331 Fix missing packages in manageiq-ansible-venv
  lib/manageiq/rpm_build/generate_ansible_venv.rb
  rpm_spec/manageiq.spec.in
  rpm_spec/subpackages/manageiq-ansible-venv
Labels: bug

#333 Upgrade ansible-runner to 2.3.0
  Dockerfile
  lib/manageiq/rpm_build/generate_ansible_venv.rb
  rpm_spec/manageiq.spec.in
  rpm_spec/subpackages/manageiq-ansible-venv
Labels: enhancement

#335 Force the sticky bit on /tmp
  Dockerfile
Labels: bug

#336 Force installation and usage of postgresql 13 for appliance rpm
  rpm_spec/subpackages/manageiq-appliance
  rpm_spec/subpackages/manageiq-core
Labels: bug, oparin/yes?

#334 Prefer building in mock rather than a container with rpmbuild
  packages/repmgr13/Dockerfile
  packages/repmgr13/README
  packages/repmgr13/container-assets/build.sh
Labels: developer

#337 Add a purger for the nightly builds and run it before updating the RPM repo
  Gemfile
  bin/build.rb
  bin/nightly_build_purger.rb
  lib/manageiq/rpm_build.rb
  lib/manageiq/rpm_build/nightly_build_purger.rb
  spec/lib/manageiq/rpm_build/nightly_build_purger_spec.rb
Labels: enhancement

#341 Fix repmgr build in mock
  packages/repmgr13/README
  packages/repmgr13/repmgr.spec
Labels: bug

#342 Bump release version due to change in buildrequires
  packages/repmgr13/repmgr.spec
Labels: bug, dependencies

#338 Script building all of the extra RPM packages
  .gitignore
  bin/build_extra_package.rb
  lib/manageiq/rpm_build/extra_package.rb
  packages/kafka/sources
  packages/python-bambou/sources
  packages/python-pylxca/sources
  packages/python-unittest2/python-unittest2.spec
  packages/python-unittest2/sources
  packages/python-unittest2/unittest2-1.1.0-backport-tests-from-py3.5.patch
  packages/python-unittest2/unittest2-1.1.0-conditionalize-traceback2.patch
  packages/python-unittest2/unittest2-1.1.0-remove-argparse-from-requires.patch
  packages/python-vspk/sources
  packages/qpid-proton/licenses.xml
  packages/qpid-proton/proton.patch
  packages/qpid-proton/qpid-proton.spec
  packages/qpid-proton/sources
  packages/repmgr13/sources
  packages/wmi/sources
  packages/wmi/wmi.spec
Labels: enhancement

#339 Add Postgres 10.21
  packages/postgresql/Makefile.regress
  packages/postgresql/generate-pdf.sh
  packages/postgresql/generate-sources.sh
  packages/postgresql/hstore-plperl-data-dumper.patch
  packages/postgresql/postgresql-10.15-contrib-dblink-expected-out.patch
  packages/postgresql/postgresql-10.21.tar.bz2.sha256
  packages/postgresql/postgresql-13.7.tar.bz2.sha256
  packages/postgresql/postgresql-14.3.tar.bz2.sha256
  packages/postgresql/postgresql-9.6.24.tar.bz2.sha256
  packages/postgresql/postgresql-bashprofile
  packages/postgresql/postgresql-external-libpq.patch
  packages/postgresql/postgresql-logging.patch
  packages/postgresql/postgresql-man.patch
  packages/postgresql/postgresql-pgcrypto-openssl3-tests.patch
  packages/postgresql/postgresql-server-pg_config.patch
  packages/postgresql/postgresql-var-run-socket.patch
  packages/postgresql/postgresql.pam
  packages/postgresql/postgresql.spec
  packages/postgresql/postgresql.tmpfiles.d
  packages/postgresql/rpm-pgsql.patch
  packages/postgresql/sources
Labels: enhancement

#344 Lock down license_finder to 7.0.1
  lib/manageiq/rpm_build/generate_gemset.rb
Labels: bug, morphy/yes, najdorf/yes, oparin/yes
