Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2022-09, with the labels that each got.

#295 Not really sure why this is here, we specify ~>3.0
  lib/manageiq/rpm_build/generate_gemset.rb
Labels: technical debt

#301 Remove vendored jquery 1.x
  lib/manageiq/rpm_build/generate_gemset.rb
Labels: enhancement, security fix

#304 Enable ruby 3 for rpm build
  Dockerfile
Labels: ruby3
