Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2022-12, with the labels that each got.

#347 Add Ansible 5.4.0-3
  config/options.yml
  lib/manageiq/rpm_build/extra_package.rb
  packages/ansible/ansible.spec
  packages/ansible/sources
Labels: dependencies, morphy/yes, najdorf/yes, oparin/yes

#348 Lockdown ansible to 5.4.0-3
  Dockerfile
  rpm_spec/subpackages/manageiq-ansible-venv
Labels: bug, morphy/yes?, najdorf/yes?, oparin/yes

#345 Force the default build settings
  .gitignore
  packages/postgresql/postgresql.spec
Labels: bug

#351 Update tokens for build_rpms workflow
  .github/workflows/build_rpms.yaml
Labels: developer

#360 Update nokogiri to 1.13.10
  Gemfile
Labels: dependencies, security fix

#362 Fix incorrect token names in workflows
  .github/workflows/build_rpms.yaml
  .github/workflows/ci.yaml
Labels: bug, najdorf/yes, oparin/yes
