Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2022-02, with the labels that each got.

#263 Add Build History Graph to README.md
  README.md
Labels: developer, test

#264 Fix issue with release script not updating nightly baseurl values
  lib/tasks/release.rake
  packages/manageiq-release/manageiq-14-najdorf.repo
Labels: bug

#266 Bump ubi to 8.5
  Dockerfile
  packages/manageiq-ansible-venv/Dockerfile
Labels: enhancement, najdorf/yes?

#242 Update node version
  Dockerfile
Labels: dependencies

#267 [NAJDORF] Drop kafka dependency due to log4j security issues
  rpm_spec/subpackages/manageiq-appliance
Labels: dependencies, morphy/yes?, security

#269 Skip symlinks in gems dir when copying systemd files
  rpm_spec/manageiq.spec.in
Labels: bug, najdorf/yes

#271 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
