Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2022-08, with the labels that each got.

#291 Remove manageiq-initialize.service from rpm specs
  rpm_spec/subpackages/manageiq-appliance
  rpm_spec/subpackages/manageiq-core-services
Labels: bug

#296 [oparin] Bundle without development and test in production and add appliance
  lib/manageiq/rpm_build/generate_gemset.rb
Labels: enhancement

#297 Bundle without development and test in production and add appliance
  lib/manageiq/rpm_build/generate_gemset.rb
Labels: enhancement

#293 Server certs need to be group readable
  rpm_spec/subpackages/manageiq-core
Labels: bug, najdorf/yes?, oparin/yes?

#299 LicenseFinder ignore dev and test bundler groups
  lib/manageiq/rpm_build/generate_gemset.rb
Labels: bug

#300 Don't add anything in rpm_cache directory to the docker image
  .dockerignore
Labels: developer
