Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2022-10, with the labels that each got.

#310 manageiq-messaging-ready rpm_specs support
  rpm_spec/subpackages/manageiq-appliance
  rpm_spec/subpackages/manageiq-core-services
Labels: enhancement

#311 Sync python updates
  packages/manageiq-ansible-venv/requirements.txt
Labels: dependencies

#314 Update building of manageiq-ansible-venv
  packages/manageiq-ansible-venv/Dockerfile
  packages/manageiq-ansible-venv/README.md
  packages/manageiq-ansible-venv/container-assets/build.sh
  packages/manageiq-ansible-venv/manageiq-ansible-venv.spec
Labels: enhancement

#303 Add a nightly rpm build script
  .github/workflows/build_rpms.yaml
Labels: developer

#316 Fix unclosed substitution
  .github/workflows/build_rpms.yaml
Labels: bug

#317 Fix workflow bug
  .github/workflows/build_rpms.yaml
Labels: bug

#325 Upgrade to Kafka v3.3.1 and build for EL9
  config/options.yml
  packages/kafka/README
  packages/kafka/kafka.spec
Labels: dependencies

#319 Move manageiq-ansible-venv as a subpackage under manageiq rpm
  Dockerfile
  bin/build.rb
  config/exclude_ansible-venv
  config/requirements.txt
  lib/manageiq/rpm_build.rb
  lib/manageiq/rpm_build/generate_ansible_venv.rb
  lib/manageiq/rpm_build/generate_tar_files.rb
  lib/manageiq/rpm_build/helper.rb
  packages/manageiq-ansible-venv/Dockerfile
  packages/manageiq-ansible-venv/README.md
  packages/manageiq-ansible-venv/container-assets/build.sh
  packages/manageiq-ansible-venv/manageiq-ansible-venv.spec
  rpm_spec/manageiq.spec.in
  rpm_spec/subpackages/manageiq-ansible-venv
  rpm_spec/subpackages/manageiq-core
Labels: enhancement

#327 Remove our copy of smem, newer versions are available in epel.
  config/options.yml
  packages/smem/smem-1.5-python3path.patch
  packages/smem/smem.spec
Labels: dependencies

#328 Reduce the verbosity of the py3_shebang_fix
  rpm_spec/manageiq.spec.in
Labels: cleanup

#329 Allow for EL9 (UBI9) RPMs in the v16 repo
  config/options.yml
Labels: dependencies
