Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2022-01, with the labels that each got.

#245 Lockdown bundler due to build failure
  Dockerfile
Labels: bug

#246 Ensure that the bundler version in the script matches the container
  lib/manageiq/rpm_build/generate_gemset.rb
Labels: bug, technical debt

#243 Changes made to support s390x platform
  Dockerfile
Labels: enhancement

#249 Unlock bundler now that 2.3.6 has been released
  Dockerfile
Labels: enhancement, morphy/yes
