Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2023-04, with the labels that each got.

#381 [WIP] Upgrade Node v14 to v16
  Dockerfile
Labels: wip

#387 Switch to IBM Cloud as the upload destination
  config/options.yml
  lib/manageiq/rpm_build/rpm_repo.rb
  lib/manageiq/rpm_build/s3_common.rb
Labels: enhancement, oparin/yes?, petrosian/yes?

#388 This doesn't appear to be an option after npm upgrade
  lib/manageiq/rpm_build/generate_gemset.rb
Labels: bug

#389 Remove more references to python2.7
  Dockerfile
  lib/manageiq/rpm_build/generate_core.rb
Labels: bug
