Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2023-06, with the labels that each got.

#395 Allow workflow_dispatch GHA event
  .github/workflows/ci.yaml
Labels: test, petrosian/yes

#396 Revert "Merge pull request #392 from bdunne/revert_275"
  lib/manageiq/rpm_build/generate_core.rb
Labels: bug

#397 [MORPHY] Add Ansible 5.4.0-3
  config/options.yml
  packages/ansible/ansible.spec
  packages/ansible/sources
Labels: dependencies

#398 [MORPHY] Switch to IBM Cloud as the upload destination
  config/options.yml
  lib/manageiq/rpm_build/rpm_repo.rb
  lib/manageiq/rpm_build/s3_common.rb
Labels: enhancement

#400 [MORPHY] Lockdown ansible to 5.4.0-3
  Dockerfile
  rpm_spec/subpackages/manageiq-core
Labels: bug
