Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2023-09, with the labels that each got.

#417 Update actions/checkout version to v4
  .github/workflows/build_rpms.yaml
  .github/workflows/ci.yaml
Labels: test

#419 Revert "Lock down to UBI 8.8-1032"
  Dockerfile
Labels: dependencies

#420 Drop s390x hack now that we are on yarn 4
  scripts/npm_registry/yarn_registry_cleanup.sh
  scripts/npm_registry/yarn_registry_setup.sh
Labels: technical debt, quinteros/yes?
