Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2023-08, with the labels that each got.

#410 Reverts a962a14350ad89d09f2d30a5983a08cd57f53e56
  lib/manageiq/rpm_build/generate_core.rb
Labels: bug, petrosian/yes

#406 declare rpm dependencies for creating user
  rpm_spec/subpackages/manageiq-core
Labels: dependencies

#413 Fix RPM spec require parsing issue
  rpm_spec/subpackages/manageiq-core
Labels: bug, quinteros/yes?

#414 core-utils is coreutils on appliances and coreutils-single on containers
  rpm_spec/subpackages/manageiq-core
Labels: bug, quinteros/yes?

#416 Lock down to UBI 8.8-1032
  Dockerfile
Labels: bug, morphy/yes?, petrosian/yes?, quinteros/yes?

#415 Add subuid/subgid for the manageiq user
  rpm_spec/subpackages/manageiq-appliance
Labels: bug, quinteros/yes?
