Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2023-03, with the labels that each got.

#307 Create a manageiq home directory
  rpm_spec/subpackages/manageiq-core
Labels: bug, stale

#385 If the directory already exists, preinstall script fails
  rpm_spec/subpackages/manageiq-core
Labels: bug, petrosian/yes?

#386 Reduce memory usage of nightly build purger
  lib/manageiq/rpm_build/nightly_build_purger.rb
Labels: bug
