Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2023-07, with the labels that each got.

#401 Add Podman as dependency for manageiq-appliance
  rpm_spec/subpackages/manageiq-appliance
Labels: enhancement

#402 Remove references to yarn 1.22.18
  lib/manageiq/rpm_build/generate_core.rb
Labels: bug

#403 Bump ipaddress python package
  config/requirements.txt
Labels: dependencies, morphy/yes?, petrosian/yes?

#407 Registry is set differently for diffrent yarn versions
  scripts/npm_registry/yarn_registry_cleanup.sh
  scripts/npm_registry/yarn_registry_setup.sh
Labels: bug

#409 Ensure yarn.lock is not updated by yarn install
  lib/manageiq/rpm_build/generate_core.rb
Labels: bug, petrosian/yes
