Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2024-01, with the labels that each got.

#435 Add manageiq user to disk group
  rpm_spec/subpackages/manageiq-appliance
Labels: bug, quinteros/yes?

#438 Add ansible-core 2.12.7 to our repos
  config/options.yml
Labels: bug, dependencies, morphy/yes?, quinteros/yes?

#437 Faster rpm build step 1
  Dockerfile
  container-assets/Add-js-rb-filtering-on-top-of-4.19.1.patch
  lib/manageiq/rpm_build/generate_tar_files.rb
  rpm_spec/manageiq.spec.in
Labels: performance

#429 Ruby 3.1
  .github/workflows/ci.yaml
  Dockerfile
  config/options.yml
  lib/manageiq/rpm_build/extra_package.rb
  lib/manageiq/rpm_build/generate_core.rb
  packages/qpid-proton/licenses.xml
  packages/qpid-proton/proton.patch
  packages/qpid-proton/qpid-proton.spec
  packages/qpid-proton/sources
  rpm_spec/subpackages/manageiq-core
  rpm_spec/subpackages/manageiq-gemset
Labels: dependencies

#439 python cryptography requires rust
  Dockerfile
Labels: bug, dependencies
