Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2024-09, with the labels that each got.

#478 Fix service ui productization symlinking
  lib/manageiq/rpm_build/generate_core.rb
Labels: bug

#495 Update ansible requirements.txt for vmware aws
  config/requirements.txt
Labels: bug

#503 Update azure keyvault to avoid parsing error
  config/requirements.txt
Labels: bug

#506 Add manageiq_podman_cleanup oneshot service
  rpm_spec/subpackages/manageiq-appliance
  rpm_spec/subpackages/manageiq-core-services
Labels: bug, radjabov/yes?

#493 Python requirements update
  bin/requirements.rb
  config/requirements.txt
Labels: enhancement, dependencies

#508 Update requirements for python dependencies
  bin/requirements.rb
  config/requirements.txt
Labels: dependencies, security fix

#509 System rpm updates for paramiko and zipp
  bin/requirements.rb
  config/requirements.txt
  rpm_spec/subpackages/manageiq-ansible-venv
Labels: dependencies, security fix

#510 Fix performance issue of looking up rpms
  bin/requirements.rb
Labels: performance
