Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2024-11, with the labels that each got.

#517 Build rpms using ruby 3.3
  .github/workflows/ci.yaml
  Dockerfile
  rpm_spec/subpackages/manageiq-core
Labels: enhancement, dependencies

#520 openssl-libs is already installed in newer UBI9
  Dockerfile
Labels: bug, radjabov/yes?

#521 [quinteros] Lock down to ruby 3.0.4 from Appstream
  Dockerfile
Labels: bug

#523 [RADJABOV] Fix radjabov refs by reverting the initial changes to the branch
  Dockerfile
  config/options.yml
Labels: bug
