Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2025-01, with the labels that each got.

#538 Fix issues where exitstatus could be nil
  lib/manageiq/rpm_build/helper.rb
Labels: bug

#505 Add documentation on how to build a hotfix
  README.md
Labels: documentation

#539 [morphy] env is not defined in this version
  lib/manageiq/rpm_build/helper.rb
Labels: bug

#541 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: developer
