Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2025-02, with the labels that each got.

#545 Set SECRET_KEY_BASE_DUMMY=1 for random value for build with rails 7.1
  Dockerfile
Labels: bug, rails7.1

#546 Add libyaml-devel for psych 5+ broken in #528
  Dockerfile
Labels: bug

#547 Exit the user entrypoint on non-zero exit code
  container-assets/user-entrypoint.sh
Labels: bug

#548 Sort the packages correctly
  Dockerfile
Labels: cleanup

#550 Builds frequently fail at git clean with binding.cpp being the only warning
  lib/manageiq/rpm_build/generate_core.rb
Labels: bug
