Repository ManageIQ/manageiq-rpm_build, pull requests merged in 2025-05, with the labels that each got.

#562 Loosen psych dependency
  Gemfile
Labels: dependencies, spassky/yes?

#563 Upgrade from Node v18 to v20
  Dockerfile
Labels: dependencies

#565 [spassky] Switch to openssl from CentOS Stream since it's newer
  Dockerfile
Labels: bug
